version: '3'
services:
  magicmirror:
    container_name: magicmirror
    image: karsten13/magicmirror:latest
    restart: unless-stopped
    shm_size: "128mb"
    env_file:
      - ./secret/secret.env
    volumes:
      - ./config:/opt/magic_mirror/config
      - ./modules:/opt/magic_mirror/modules
      - ./css:/opt/magic_mirror/css
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /opt/vc:/opt/vc/:ro
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    devices:
      - /dev/vchiq
    ports:
      - 8080:8080
    command:
      - npm
      - run
      - start
    environment:
      - LD_LIBRARY_PATH=/opt/vc/lib
      - DISPLAY=unix:0.0

